name: Deploy GitHub Pages

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name "Thais"
          git config --global user.email "thaismoura83@hotmail.com"

      # (Opcional) Limpar o diretório de trabalho
      - name: Clean working directory
        run: |
          git clean -fdx

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./thaistech/thaistech  # Certifique-se de que esse diretório contém os arquivos para GitHub Pages
          publish_branch: gh-pages  # Especificando o branch de destino para GitHub Pages
