name: Update README and Publish to GitHub Pages

on:
  schedule:  # Execute every 12 hours
    - cron: "* */12 * * *"  # Isso irá rodar o workflow a cada 12 horas automaticamente

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step to update README.md content (customized for your profile)
      - name: Update README.md content
        run: |
          echo "# Bem-vindo ao meu perfil, thaistech!" > README.md
          echo "Aqui você pode ver meus projetos e contribuições no GitHub." >> README.md
          echo "" >> README.md
          echo "## Projetos em Destaque" >> README.md
          echo "- [Projeto 1: thaismoura](https://github.com/thaistech/thaismoura)" >> README.md
          echo "- [Projeto 2: Outro Projeto](https://github.com/thaistech/outro-projeto)" >> README.md

      # Step to commit and push the updated README
      - name: Commit and push the updated README
        run: |
          git config --global user.name "Thais"
          git config --global user.email "thaismoura83@hotmail.com"
          git add README.md
          git commit -m "Atualizar README.md com projetos e informações" || echo "Nada para commitar"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/thaistech/thaismoura.git HEAD:main  # Altere 'main' para a sua branch, se necessário

      # Step to deploy to GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages  # Ou a branch que você usa para GitHub Pages
          build_dir: .  # Configuração da pasta onde o arquivo README.md está (normalmente a raiz)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
